# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd832db53153530f87643c5f8ce2a7772eb24d2d30bcb444ceaa44dac136b136aea207cc8880827c3007b3a7712d6c5c03c0645d0b246f2d6dbc0b8c90507940

test:
  secret_key_base: d1b7846774acd93e4885192a65c45bedaf75b22e7807936f197d3e5e699172ccaeab6f38c85129f8f423854a02780fdf774caa6aa438702cf69ae2d53a14c74e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
